name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and unzip template
        run: |
          wget https://www.tooplate.com/zip-templates/2096_individual.zip -O template.zip
          unzip template.zip -d website

      - name: Deploy to GitHub Pages
        run: |
          cd website/2096_individual
          git init
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy website"
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
